// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: websocket.proto

package websocket

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WebsocketService_PublishDocumentEvent_FullMethodName = "/websocket.WebsocketService/PublishDocumentEvent"
)

// WebsocketServiceClient is the client API for WebsocketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WebsocketServiceClient interface {
	PublishDocumentEvent(ctx context.Context, in *DocumentEvent, opts ...grpc.CallOption) (*EventResponse, error)
}

type websocketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWebsocketServiceClient(cc grpc.ClientConnInterface) WebsocketServiceClient {
	return &websocketServiceClient{cc}
}

func (c *websocketServiceClient) PublishDocumentEvent(ctx context.Context, in *DocumentEvent, opts ...grpc.CallOption) (*EventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventResponse)
	err := c.cc.Invoke(ctx, WebsocketService_PublishDocumentEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WebsocketServiceServer is the server API for WebsocketService service.
// All implementations must embed UnimplementedWebsocketServiceServer
// for forward compatibility.
type WebsocketServiceServer interface {
	PublishDocumentEvent(context.Context, *DocumentEvent) (*EventResponse, error)
	mustEmbedUnimplementedWebsocketServiceServer()
}

// UnimplementedWebsocketServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWebsocketServiceServer struct{}

func (UnimplementedWebsocketServiceServer) PublishDocumentEvent(context.Context, *DocumentEvent) (*EventResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishDocumentEvent not implemented")
}
func (UnimplementedWebsocketServiceServer) mustEmbedUnimplementedWebsocketServiceServer() {}
func (UnimplementedWebsocketServiceServer) testEmbeddedByValue()                          {}

// UnsafeWebsocketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WebsocketServiceServer will
// result in compilation errors.
type UnsafeWebsocketServiceServer interface {
	mustEmbedUnimplementedWebsocketServiceServer()
}

func RegisterWebsocketServiceServer(s grpc.ServiceRegistrar, srv WebsocketServiceServer) {
	// If the following call pancis, it indicates UnimplementedWebsocketServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WebsocketService_ServiceDesc, srv)
}

func _WebsocketService_PublishDocumentEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DocumentEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WebsocketServiceServer).PublishDocumentEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WebsocketService_PublishDocumentEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WebsocketServiceServer).PublishDocumentEvent(ctx, req.(*DocumentEvent))
	}
	return interceptor(ctx, in, info, handler)
}

// WebsocketService_ServiceDesc is the grpc.ServiceDesc for WebsocketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WebsocketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "websocket.WebsocketService",
	HandlerType: (*WebsocketServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishDocumentEvent",
			Handler:    _WebsocketService_PublishDocumentEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "websocket.proto",
}
